apiVersion: v1
kind: Service
metadata:
  name: hw-go-http
  namespace: ricxapp
  labels:
    app: hw-go
    xapp: hw-go
spec:
  type: ClusterIP
  selector:
    app: hw-go
  ports:
  - name: http-api
    port: 8080
    targetPort: 8080
    protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: hw-go-rmr
  namespace: ricxapp
  labels:
    app: hw-go
    xapp: hw-go
spec:
  type: ClusterIP
  selector:
    app: hw-go
  ports:
  - name: rmr-data
    port: 4560
    targetPort: 4560
    protocol: TCP
  - name: rmr-route
    port: 4561
    targetPort: 4561
    protocol: TCP
