apiVersion: v1
entries:
  ric-common:
  - apiVersion: v1
    created: "2025-11-19T07:11:22.616124516+08:00"
    description: Common templates for inclusion in other charts
    digest: 917c78dfd89d49711eda60253f84bb582fc387741e8a3b4e0f052089691e0256
    name: ric-common
    urls:
    - ric-common-3.3.2.tgz
    version: 3.3.2
generated: "2025-11-19T07:11:22.61478256+08:00"
